---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: test-aug1-chatbot
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-aug1-chatbot 
  name: test-aug1-chatbot
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi