apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: test-aug1-chatbot
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-aug1-chatbot 
  name: test-aug1-chatbot
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: test-aug1-chatbot 
